addresses = [
    {
        "name": "NET_199.40.1.0_24",
        "q_origin_key": "NET_199.40.1.0_24",
        "uuid": "de0fca6a-baa0-51e9-eb11-ae6b8930fc1f",
        "subnet": "199.40.1.0 255.255.255.0",
        "type": "ipmask",
        "sub-type": "sdn",
        "clearpass-spt": "unknown",
        "start-mac": "00:00:00:00:00:00",
        "end-mac": "00:00:00:00:00:00",
        "country": "",
        "cache-ttl": 0,
        "sdn": "",
        "fsso-group": [],
        "interface": "port4",
        "comment": "test comment",
        "visibility": "enable",
        "associated-interface": "",
        "color": 0,
        "filter": "",
        "sdn-addr-type": "private",
        "obj-id": "",
        "list": [],
        "tagging": [],
        "allow-routing": "disable",
    },
    {
        "name": "NET_198.141.216.0_22",
        "q_origin_key": "NET_198.141.216.0_22",
        "uuid": "de0fca6a-baa0-51e9-eb11-ae6b8930fc1f",
        "subnet": "198.141.216.0 255.255.252.0",
        "type": "ipmask",
        "sub-type": "sdn",
        "clearpass-spt": "unknown",
        "start-mac": "00:00:00:00:00:00",
        "end-mac": "00:00:00:00:00:00",
        "country": "",
        "cache-ttl": 0,
        "sdn": "",
        "fsso-group": [],
        "interface": "",
        "comment": "",
        "visibility": "enable",
        "associated-interface": "",
        "color": 0,
        "filter": "",
        "sdn-addr-type": "private",
        "obj-id": "",
        "list": [],
        "tagging": [],
        "allow-routing": "disable",
    },
    {
        "name": "RANGE_10.188.128.106-108",
        "q_origin_key": "RANGE_10.188.128.106-108",
        "uuid": "d3f9bb82-3d20-51ea-98fa-4a8464d34087",
        "type": "iprange",
        "sub-type": "sdn",
        "clearpass-spt": "unknown",
        "start-mac": "00:00:00:00:00:00",
        "end-mac": "00:00:00:00:00:00",
        "start-ip": "10.188.128.106",
        "end-ip": "10.188.128.108",
        "country": "",
        "cache-ttl": 0,
        "sdn": "",
        "fsso-group": [],
        "interface": "",
        "comment": "snke 20200122 DPDHL 2020012170002501",
        "visibility": "enable",
        "associated-interface": "",
        "color": 0,
        "filter": "",
        "sdn-addr-type": "private",
        "obj-id": "",
        "list": [],
        "tagging": [],
        "allow-routing": "disable",
    },
    {
        "name": "FQDN_aadcdn.msauth.net",
        "q_origin_key": "aadcdn.msauth.net",
        "uuid": "2235b9c8-0fa7-51eb-d7e7-d84a96dd26d2",
        "type": "fqdn",
        "sub-type": "sdn",
        "clearpass-spt": "unknown",
        "start-mac": "00:00:00:00:00:00",
        "end-mac": "00:00:00:00:00:00",
        "fqdn": "aadcdn.msauth.net",
        "country": "",
        "cache-ttl": 0,
        "sdn": "",
        "fsso-group": [],
        "interface": "",
        "obj-type": "ip",
        "comment": "",
        "associated-interface": "",
        "color": 19,
        "filter": "",
        "sdn-addr-type": "private",
        "obj-id": "",
        "list": [],
        "tagging": [],
        "allow-routing": "disable",
        "fabric-object": "disable",
    },
    {
        "name": "FQDN_golem.de",
        "q_origin_key": "golem.de",
        "uuid": "2235b9c8-0fa7-51eb-d7e7-d84a96dd26d2",
        "type": "fqdn",
        "sub-type": "sdn",
        "clearpass-spt": "unknown",
        "start-mac": "00:00:00:00:00:00",
        "end-mac": "00:00:00:00:00:00",
        "fqdn": "aadcdn.msauth.net",
        "country": "",
        "cache-ttl": 0,
        "sdn": "",
        "fsso-group": [],
        "interface": "port4",
        "obj-type": "ip",
        "comment": "",
        "associated-interface": "",
        "color": 19,
        "filter": "",
        "sdn-addr-type": "private",
        "obj-id": "",
        "list": [],
        "tagging": [],
        "allow-routing": "disable",
        "fabric-object": "disable",
    },
    {
        "name": "NET_172.16.240.120_29",
        "q_origin_key": "NET_172.16.240.120_29",
        "uuid": "4a609a5c-05a2-51ec-e7de-7ecd5e5c96cc",
        "subnet": "172.16.240.120 255.255.255.248",
        "type": "ipmask",
        "sub-type": "sdn",
        "clearpass-spt": "unknown",
        "start-mac": "00:00:00:00:00:00",
        "end-mac": "00:00:00:00:00:00",
        "country": "",
        "cache-ttl": 0,
        "sdn": "",
        "fsso-group": [],
        "interface": "",
        "obj-type": "ip",
        "comment": "",
        "associated-interface": "",
        "color": 0,
        "filter": "",
        "sdn-addr-type": "private",
        "obj-id": "",
        "list": [],
        "tagging": [],
        "allow-routing": "disable",
        "fabric-object": "disable",
    },
]

address_groups = [
    {
        "name": "test group 1",
        "q_origin_key": "test group 1",
        "type": "default",
        "uuid": "22481460-0fa7-51eb-d5d8-511a23d9e986",
        "member": [
            {
                "name": "FQDN_aadcdn.msauth.net",
                "q_origin_key": "FQDN_aadcdn.msauth.net",
            },
            {
                "name": "NET_198.141.216.0_22",
                "q_origin_key": "NET_198.141.216.0_22",
            },
        ],
        "comment": "",
        "exclude": "disable",
        "exclude-member": [],
        "color": 3,
        "tagging": [],
        "allow-routing": "disable",
        "fabric-object": "disable",
    },
    {
        "name": "test group 2",
        "q_origin_key": "test group 2",
        "type": "default",
        "uuid": "22481460-0fa7-51eb-d5d8-511a23d9e986",
        "member": [{"name": "test group 1", "q_origin_key": "test group 1"}],
        "comment": "",
        "exclude": "disable",
        "exclude-member": [],
        "color": 3,
        "tagging": [],
        "allow-routing": "disable",
        "fabric-object": "disable",
    },
    {
        "name": "test group 3",
        "q_origin_key": "test group 3",
        "type": "default",
        "uuid": "22481460-0fa7-51eb-d5d8-511a23d9e986",
        "member": [
            {"name": "test group 1", "q_origin_key": "test group 1"},
            {
                "name": "RANGE_10.188.128.106-108",
                "q_origin_key": "RANGE_10.188.128.106-108",
            },
        ],
        "comment": "",
        "exclude": "disable",
        "exclude-member": [],
        "color": 3,
        "tagging": [],
        "allow-routing": "disable",
        "fabric-object": "disable",
    },
]

address_groups_member_missing = [
    {
        "name": "test group 1",
        "q_origin_key": "test group 1",
        "type": "default",
        "uuid": "22481460-0fa7-51eb-d5d8-511a23d9e986",
        "member": [
            {
                "name": "FQDN_aadcdn.msauth.net",
                "q_origin_key": "FQDN_aadcdn.msauth.net",
            },
            {
                "name": "NET_198.141.216.0_22",
                "q_origin_key": "NET_198.141.216.0_22",
            },
        ],
        "comment": "",
        "exclude": "disable",
        "exclude-member": [],
        "color": 3,
        "tagging": [],
        "allow-routing": "disable",
        "fabric-object": "disable",
    },
    {
        "name": "test group 4",
        "q_origin_key": "test group 4",
        "type": "default",
        "uuid": "22481460-0fa7-51eb-d5d8-511a23d9e986",
        "member": [
            {"name": "test group 1", "q_origin_key": "test group 1"},
            {"name": "missing member", "q_origin_key": "missing member"},
        ],
        "comment": "",
        "exclude": "disable",
        "exclude-member": [],
        "color": 3,
        "tagging": [],
        "allow-routing": "disable",
        "fabric-object": "disable",
    },
]

interfaces = [
    {
        "name": "port4",
        "q_origin_key": "port4",
        "vdom": "root",
        "vrf": 0,
        "cli-conn-status": 0,
        "fortilink": "disable",
        "mode": "static",
        "distance": 5,
        "priority": 0,
        "dhcp-relay-interface-select-method": "auto",
        "dhcp-relay-interface": "",
        "dhcp-relay-service": "disable",
        "dhcp-relay-ip": "",
        "dhcp-relay-type": "regular",
        "dhcp-relay-agent-option": "enable",
        "management-ip": "0.0.0.0 0.0.0.0",
        "ip": "10.187.88.52 255.255.255.240",
        "allowaccess": "ping probe-response",
        "gwdetect": "disable",
        "ping-serv-status": 0,
        "detectserver": "",
        "detectprotocol": "ping",
        "ha-priority": 1,
        "fail-detect": "disable",
        "fail-detect-option": "link-down",
        "fail-alert-method": "link-down",
        "fail-action-on-extender": "soft-restart",
        "fail-alert-interfaces": [],
        "dhcp-client-identifier": "",
        "dhcp-renew-time": 0,
        "ipunnumbered": "0.0.0.0",
        "username": "",
        "pppoe-unnumbered-negotiate": "enable",
        "password": "",
        "idle-timeout": 0,
        "detected-peer-mtu": 0,
        "disc-retry-timeout": 1,
        "padt-retry-timeout": 1,
        "service-name": "",
        "ac-name": "",
        "lcp-echo-interval": 5,
        "lcp-max-echo-fails": 3,
        "defaultgw": "enable",
        "dns-server-override": "enable",
        "auth-type": "auto",
        "pptp-client": "disable",
        "pptp-user": "",
        "pptp-password": "",
        "pptp-server-ip": "0.0.0.0",
        "pptp-auth-type": "auto",
        "pptp-timeout": 0,
        "arpforward": "enable",
        "ndiscforward": "enable",
        "broadcast-forward": "disable",
        "bfd": "global",
        "bfd-desired-min-tx": 250,
        "bfd-detect-mult": 3,
        "bfd-required-min-rx": 250,
        "l2forward": "disable",
        "icmp-send-redirect": "enable",
        "icmp-accept-redirect": "enable",
        "vlanforward": "disable",
        "stpforward": "disable",
        "stpforward-mode": "rpl-all-ext-id",
        "ips-sniffer-mode": "disable",
        "ident-accept": "disable",
        "ipmac": "disable",
        "subst": "disable",
        "macaddr": "",
        "substitute-dst-mac": "00:00:00:00:00:00",
        "speed": "auto",
        "status": "up",
        "netbios-forward": "disable",
        "wins-ip": "0.0.0.0",
        "type": "physical",
        "dedicated-to": "none",
        "trust-ip-1": "0.0.0.0 0.0.0.0",
        "trust-ip-2": "0.0.0.0 0.0.0.0",
        "trust-ip-3": "0.0.0.0 0.0.0.0",
        "trust-ip6-1": "::/0",
        "trust-ip6-2": "::/0",
        "trust-ip6-3": "::/0",
        "mtu-override": "disable",
        "mtu": 1500,
        "ring-rx": 0,
        "ring-tx": 0,
        "wccp": "disable",
        "netflow-sampler": "disable",
        "sflow-sampler": "disable",
        "drop-overlapped-fragment": "disable",
        "drop-fragment": "disable",
        "src-check": "enable",
        "sample-rate": 2000,
        "polling-interval": 20,
        "sample-direction": "both",
        "explicit-web-proxy": "disable",
        "explicit-ftp-proxy": "disable",
        "proxy-captive-portal": "disable",
        "tcp-mss": 0,
        "inbandwidth": 0,
        "outbandwidth": 0,
        "egress-shaping-profile": "",
        "ingress-shaping-profile": "",
        "disconnect-threshold": 0,
        "spillover-threshold": 0,
        "ingress-spillover-threshold": 0,
        "weight": 0,
        "interface": "",
        "external": "disable",
        "vlanid": 0,
        "forward-domain": 0,
        "remote-ip": "0.0.0.0 0.0.0.0",
        "member": [],
        "lacp-mode": "active",
        "lacp-ha-slave": "enable",
        "lacp-speed": "slow",
        "min-links": 1,
        "min-links-down": "operational",
        "algorithm": "L4",
        "link-up-delay": 50,
        "priority-override": "enable",
        "devindex": 6,
        "vindex": 0,
        "description": "",
        "alias": "CN",
        "security-mode": "none",
        "captive-portal": 0,
        "security-mac-auth-bypass": "disable",
        "security-external-web": "",
        "security-external-logout": "",
        "replacemsg-override-group": "",
        "security-redirect-url": "",
        "security-exempt-list": "",
        "security-groups": [],
        "device-identification": "disable",
        "device-user-identification": "enable",
        "lldp-reception": "vdom",
        "lldp-transmission": "vdom",
        "lldp-network-policy": "",
        "broadcast-forticlient-discovery": "disable",
        "estimated-upstream-bandwidth": 0,
        "estimated-downstream-bandwidth": 0,
        "vrrp-virtual-mac": "disable",
        "vrrp": [],
        "role": "undefined",
        "snmp-index": 4,
        "secondary-IP": "disable",
        "secondaryip": [],
        "preserve-session-route": "disable",
        "auto-auth-extension-device": "disable",
        "ap-discover": "enable",
        "fortilink-stacking": "enable",
        "fortilink-neighbor-detect": "fortilink",
        "fortilink-split-interface": "enable",
        "internal": 0,
        "fortilink-backup-link": 0,
        "switch-controller-access-vlan": "disable",
        "switch-controller-traffic-policy": "",
        "switch-controller-rspan-mode": "disable",
        "switch-controller-igmp-snooping": "disable",
        "switch-controller-igmp-snooping-proxy": "disable",
        "switch-controller-igmp-snooping-fast-leave": "disable",
        "switch-controller-dhcp-snooping": "disable",
        "switch-controller-dhcp-snooping-verify-mac": "disable",
        "switch-controller-dhcp-snooping-option82": "disable",
        "switch-controller-arp-inspection": "disable",
        "switch-controller-learning-limit": 0,
        "color": 0,
        "tagging": [],
        "eip": "0.0.0.0",
        "ipv6": {
            "ip6-mode": "static",
            "nd-mode": "basic",
            "nd-cert": "",
            "nd-security-level": 0,
            "nd-timestamp-delta": 300,
            "nd-timestamp-fuzz": 1,
            "nd-cga-modifier": "0065636473612D776974682D73686132",
            "ip6-dns-server-override": "enable",
            "ip6-address": "::/0",
            "ip6-extra-addr": [],
            "ip6-allowaccess": "",
            "ip6-send-adv": "disable",
            "ip6-manage-flag": "disable",
            "ip6-other-flag": "disable",
            "ip6-max-interval": 600,
            "ip6-min-interval": 198,
            "ip6-link-mtu": 0,
            "ip6-reachable-time": 0,
            "ip6-retrans-time": 0,
            "ip6-default-life": 1800,
            "ip6-hop-limit": 0,
            "autoconf": "disable",
            "ip6-upstream-interface": "",
            "ip6-subnet": "::/0",
            "ip6-prefix-list": [],
            "ip6-delegated-prefix-list": [],
            "dhcp6-relay-service": "disable",
            "dhcp6-relay-type": "regular",
            "dhcp6-relay-ip": "",
            "dhcp6-client-options": "",
            "dhcp6-prefix-delegation": "disable",
            "dhcp6-information-request": "disable",
            "dhcp6-prefix-hint": "::/0",
            "dhcp6-prefix-hint-plt": 604800,
            "dhcp6-prefix-hint-vlt": 2592000,
            "vrrp-virtual-mac6": "disable",
            "vrip6_link_local": "::",
            "vrrp6": [],
        },
    },
    {
        "name": "port5",
        "q_origin_key": "port5",
        "vdom": "root",
        "vrf": 0,
        "cli-conn-status": 0,
        "fortilink": "disable",
        "mode": "static",
        "distance": 5,
        "priority": 0,
        "dhcp-relay-interface-select-method": "auto",
        "dhcp-relay-interface": "",
        "dhcp-relay-service": "disable",
        "dhcp-relay-ip": "",
        "dhcp-relay-type": "regular",
        "dhcp-relay-agent-option": "enable",
        "management-ip": "0.0.0.0 0.0.0.0",
        "ip": "172.16.0.52 255.255.255.248",
        "allowaccess": "ping probe-response",
        "gwdetect": "disable",
        "ping-serv-status": 0,
        "detectserver": "",
        "detectprotocol": "ping",
        "ha-priority": 1,
        "fail-detect": "disable",
        "fail-detect-option": "link-down",
        "fail-alert-method": "link-down",
        "fail-action-on-extender": "soft-restart",
        "fail-alert-interfaces": [],
        "dhcp-client-identifier": "",
        "dhcp-renew-time": 0,
        "ipunnumbered": "0.0.0.0",
        "username": "",
        "pppoe-unnumbered-negotiate": "enable",
        "password": "",
        "idle-timeout": 0,
        "detected-peer-mtu": 0,
        "disc-retry-timeout": 1,
        "padt-retry-timeout": 1,
        "service-name": "",
        "ac-name": "",
        "lcp-echo-interval": 5,
        "lcp-max-echo-fails": 3,
        "defaultgw": "enable",
        "dns-server-override": "enable",
        "auth-type": "auto",
        "pptp-client": "disable",
        "pptp-user": "",
        "pptp-password": "",
        "pptp-server-ip": "0.0.0.0",
        "pptp-auth-type": "auto",
        "pptp-timeout": 0,
        "arpforward": "enable",
        "ndiscforward": "enable",
        "broadcast-forward": "disable",
        "bfd": "global",
        "bfd-desired-min-tx": 250,
        "bfd-detect-mult": 3,
        "bfd-required-min-rx": 250,
        "l2forward": "disable",
        "icmp-send-redirect": "enable",
        "icmp-accept-redirect": "enable",
        "vlanforward": "disable",
        "stpforward": "disable",
        "stpforward-mode": "rpl-all-ext-id",
        "ips-sniffer-mode": "disable",
        "ident-accept": "disable",
        "ipmac": "disable",
        "subst": "disable",
        "macaddr": "",
        "substitute-dst-mac": "00:00:00:00:00:00",
        "speed": "auto",
        "status": "up",
        "netbios-forward": "disable",
        "wins-ip": "0.0.0.0",
        "type": "physical",
        "dedicated-to": "none",
        "trust-ip-1": "0.0.0.0 0.0.0.0",
        "trust-ip-2": "0.0.0.0 0.0.0.0",
        "trust-ip-3": "0.0.0.0 0.0.0.0",
        "trust-ip6-1": "::/0",
        "trust-ip6-2": "::/0",
        "trust-ip6-3": "::/0",
        "mtu-override": "disable",
        "mtu": 1500,
        "ring-rx": 0,
        "ring-tx": 0,
        "wccp": "disable",
        "netflow-sampler": "disable",
        "sflow-sampler": "disable",
        "drop-overlapped-fragment": "disable",
        "drop-fragment": "disable",
        "src-check": "enable",
        "sample-rate": 2000,
        "polling-interval": 20,
        "sample-direction": "both",
        "explicit-web-proxy": "disable",
        "explicit-ftp-proxy": "disable",
        "proxy-captive-portal": "disable",
        "tcp-mss": 0,
        "inbandwidth": 0,
        "outbandwidth": 0,
        "egress-shaping-profile": "",
        "ingress-shaping-profile": "",
        "disconnect-threshold": 0,
        "spillover-threshold": 0,
        "ingress-spillover-threshold": 0,
        "weight": 0,
        "interface": "",
        "external": "disable",
        "vlanid": 0,
        "forward-domain": 0,
        "remote-ip": "0.0.0.0 0.0.0.0",
        "member": [],
        "lacp-mode": "active",
        "lacp-ha-slave": "enable",
        "lacp-speed": "slow",
        "min-links": 1,
        "min-links-down": "operational",
        "algorithm": "L4",
        "link-up-delay": 50,
        "priority-override": "enable",
        "devindex": 7,
        "vindex": 0,
        "description": "",
        "alias": "DMZ",
        "security-mode": "none",
        "captive-portal": 0,
        "security-mac-auth-bypass": "disable",
        "security-external-web": "",
        "security-external-logout": "",
        "replacemsg-override-group": "",
        "security-redirect-url": "",
        "security-exempt-list": "",
        "security-groups": [],
        "device-identification": "disable",
        "device-user-identification": "enable",
        "lldp-reception": "vdom",
        "lldp-transmission": "vdom",
        "lldp-network-policy": "",
        "broadcast-forticlient-discovery": "disable",
        "estimated-upstream-bandwidth": 0,
        "estimated-downstream-bandwidth": 0,
        "vrrp-virtual-mac": "disable",
        "vrrp": [],
        "role": "dmz",
        "snmp-index": 5,
        "secondary-IP": "disable",
        "secondaryip": [],
        "preserve-session-route": "disable",
        "auto-auth-extension-device": "disable",
        "ap-discover": "enable",
        "fortilink-stacking": "enable",
        "fortilink-neighbor-detect": "fortilink",
        "fortilink-split-interface": "enable",
        "internal": 0,
        "fortilink-backup-link": 0,
        "switch-controller-access-vlan": "disable",
        "switch-controller-traffic-policy": "",
        "switch-controller-rspan-mode": "disable",
        "switch-controller-igmp-snooping": "disable",
        "switch-controller-igmp-snooping-proxy": "disable",
        "switch-controller-igmp-snooping-fast-leave": "disable",
        "switch-controller-dhcp-snooping": "disable",
        "switch-controller-dhcp-snooping-verify-mac": "disable",
        "switch-controller-dhcp-snooping-option82": "disable",
        "switch-controller-arp-inspection": "disable",
        "switch-controller-learning-limit": 0,
        "color": 0,
        "tagging": [],
        "eip": "0.0.0.0",
        "ipv6": {
            "ip6-mode": "static",
            "nd-mode": "basic",
            "nd-cert": "",
            "nd-security-level": 0,
            "nd-timestamp-delta": 300,
            "nd-timestamp-fuzz": 1,
            "nd-cga-modifier": "0065636473612D776974682D73686132",
            "ip6-dns-server-override": "enable",
            "ip6-address": "::/0",
            "ip6-extra-addr": [],
            "ip6-allowaccess": "",
            "ip6-send-adv": "disable",
            "ip6-manage-flag": "disable",
            "ip6-other-flag": "disable",
            "ip6-max-interval": 600,
            "ip6-min-interval": 198,
            "ip6-link-mtu": 0,
            "ip6-reachable-time": 0,
            "ip6-retrans-time": 0,
            "ip6-default-life": 1800,
            "ip6-hop-limit": 0,
            "autoconf": "disable",
            "ip6-upstream-interface": "",
            "ip6-subnet": "::/0",
            "ip6-prefix-list": [],
            "ip6-delegated-prefix-list": [],
            "dhcp6-relay-service": "disable",
            "dhcp6-relay-type": "regular",
            "dhcp6-relay-ip": "",
            "dhcp6-client-options": "",
            "dhcp6-prefix-delegation": "disable",
            "dhcp6-information-request": "disable",
            "dhcp6-prefix-hint": "::/0",
            "dhcp6-prefix-hint-plt": 604800,
            "dhcp6-prefix-hint-vlt": 2592000,
            "vrrp-virtual-mac6": "disable",
            "vrip6_link_local": "::",
            "vrrp6": [],
        },
    },
    {
        "name": "port1",
        "q_origin_key": "port1",
        "vdom": "root",
        "vrf": 0,
        "cli-conn-status": 0,
        "fortilink": "disable",
        "switch-controller-source-ip": "outbound",
        "mode": "static",
        "client-options": [],
        "distance": 5,
        "priority": 0,
        "dhcp-relay-interface-select-method": "auto",
        "dhcp-relay-interface": "",
        "dhcp-relay-service": "disable",
        "dhcp-relay-ip": "",
        "dhcp-relay-type": "regular",
        "dhcp-relay-agent-option": "enable",
        "management-ip": "0.0.0.0 0.0.0.0",
        "ip": "172.16.4.37 255.255.255.224",
        "allowaccess": "probe-response",
        "gwdetect": "disable",
        "ping-serv-status": 0,
        "detectserver": "",
        "detectprotocol": "ping",
        "ha-priority": 1,
        "fail-detect": "disable",
        "fail-detect-option": "link-down",
        "fail-alert-method": "link-down",
        "fail-action-on-extender": "soft-restart",
        "fail-alert-interfaces": [],
        "dhcp-client-identifier": "",
        "dhcp-renew-time": 0,
        "ipunnumbered": "0.0.0.0",
        "username": "",
        "pppoe-unnumbered-negotiate": "enable",
        "password": "",
        "idle-timeout": 0,
        "detected-peer-mtu": 0,
        "disc-retry-timeout": 1,
        "padt-retry-timeout": 1,
        "service-name": "",
        "ac-name": "",
        "lcp-echo-interval": 5,
        "lcp-max-echo-fails": 3,
        "defaultgw": "enable",
        "dns-server-override": "enable",
        "auth-type": "auto",
        "pptp-client": "disable",
        "pptp-user": "",
        "pptp-password": "",
        "pptp-server-ip": "0.0.0.0",
        "pptp-auth-type": "auto",
        "pptp-timeout": 0,
        "arpforward": "enable",
        "ndiscforward": "enable",
        "broadcast-forward": "disable",
        "bfd": "global",
        "bfd-desired-min-tx": 250,
        "bfd-detect-mult": 3,
        "bfd-required-min-rx": 250,
        "l2forward": "disable",
        "icmp-send-redirect": "enable",
        "icmp-accept-redirect": "enable",
        "vlanforward": "disable",
        "stpforward": "disable",
        "stpforward-mode": "rpl-all-ext-id",
        "ips-sniffer-mode": "disable",
        "ident-accept": "disable",
        "ipmac": "disable",
        "subst": "disable",
        "macaddr": "",
        "substitute-dst-mac": "00:00:00:00:00:00",
        "speed": "auto",
        "status": "up",
        "netbios-forward": "disable",
        "wins-ip": "0.0.0.0",
        "type": "physical",
        "dedicated-to": "none",
        "trust-ip-1": "0.0.0.0 0.0.0.0",
        "trust-ip-2": "0.0.0.0 0.0.0.0",
        "trust-ip-3": "0.0.0.0 0.0.0.0",
        "trust-ip6-1": "::\\/0",
        "trust-ip6-2": "::\\/0",
        "trust-ip6-3": "::\\/0",
        "mtu-override": "disable",
        "mtu": 1500,
        "ring-rx": 0,
        "ring-tx": 0,
        "wccp": "disable",
        "netflow-sampler": "both",
        "sflow-sampler": "disable",
        "drop-overlapped-fragment": "disable",
        "drop-fragment": "disable",
        "src-check": "enable",
        "sample-rate": 2000,
        "polling-interval": 20,
        "sample-direction": "both",
        "explicit-web-proxy": "disable",
        "explicit-ftp-proxy": "disable",
        "proxy-captive-portal": "disable",
        "tcp-mss": 0,
        "inbandwidth": 0,
        "outbandwidth": 0,
        "egress-shaping-profile": "",
        "ingress-shaping-profile": "",
        "disconnect-threshold": 0,
        "spillover-threshold": 0,
        "ingress-spillover-threshold": 0,
        "weight": 0,
        "interface": "",
        "external": "disable",
        "vlan-protocol": "8021q",
        "vlanid": 0,
        "forward-domain": 0,
        "remote-ip": "0.0.0.0 0.0.0.0",
        "member": [],
        "lacp-mode": "active",
        "lacp-ha-slave": "enable",
        "lacp-speed": "slow",
        "min-links": 1,
        "min-links-down": "operational",
        "algorithm": "L4",
        "link-up-delay": 50,
        "priority-override": "enable",
        "devindex": 3,
        "vindex": 0,
        "description": "",
        "alias": "internet",
        "security-mode": "none",
        "captive-portal": 0,
        "security-mac-auth-bypass": "disable",
        "security-external-web": "",
        "security-external-logout": "",
        "replacemsg-override-group": "",
        "security-redirect-url": "",
        "security-exempt-list": "",
        "security-groups": [],
        "device-identification": "disable",
        "device-user-identification": "enable",
        "lldp-reception": "vdom",
        "lldp-transmission": "vdom",
        "lldp-network-policy": "",
        "estimated-upstream-bandwidth": 0,
        "estimated-downstream-bandwidth": 0,
        "measured-upstream-bandwidth": 0,
        "measured-downstream-bandwidth": 0,
        "bandwidth-measure-time": 0,
        "monitor-bandwidth": "enable",
        "vrrp-virtual-mac": "disable",
        "vrrp": [],
        "role": "undefined",
        "snmp-index": 1,
        "secondary-IP": "disable",
        "secondaryip": [],
        "preserve-session-route": "disable",
        "auto-auth-extension-device": "disable",
        "ap-discover": "enable",
        "fortilink-stacking": "enable",
        "fortilink-neighbor-detect": "fortilink",
        "ip-managed-by-fortiipam": "disable",
        "managed-subnetwork-size": "256",
        "fortilink-split-interface": "enable",
        "internal": 0,
        "fortilink-backup-link": 0,
        "switch-controller-access-vlan": "disable",
        "switch-controller-traffic-policy": "",
        "switch-controller-rspan-mode": "disable",
        "switch-controller-mgmt-vlan": 4094,
        "switch-controller-igmp-snooping": "disable",
        "switch-controller-igmp-snooping-proxy": "disable",
        "switch-controller-igmp-snooping-fast-leave": "disable",
        "switch-controller-dhcp-snooping": "disable",
        "switch-controller-dhcp-snooping-verify-mac": "disable",
        "switch-controller-dhcp-snooping-option82": "disable",
        "switch-controller-arp-inspection": "disable",
        "switch-controller-learning-limit": 0,
        "switch-controller-nac": "",
        "switch-controller-feature": "none",
        "switch-controller-iot-scanning": "disable",
        "swc-vlan": 0,
        "swc-first-create": 0,
        "color": 0,
        "tagging": [],
        "eip": "0.0.0.0",
        "ipv6": {
            "ip6-mode": "static",
            "nd-mode": "basic",
            "nd-cert": "",
            "nd-security-level": 0,
            "nd-timestamp-delta": 300,
            "nd-timestamp-fuzz": 1,
            "nd-cga-modifier": "0065636473612D776974682D73686132",
            "ip6-dns-server-override": "enable",
            "ip6-address": "::\\/0",
            "ip6-extra-addr": [],
            "ip6-allowaccess": "",
            "ip6-send-adv": "disable",
            "icmp6-send-redirect": "enable",
            "ip6-manage-flag": "disable",
            "ip6-other-flag": "disable",
            "ip6-max-interval": 600,
            "ip6-min-interval": 198,
            "ip6-link-mtu": 0,
            "ip6-reachable-time": 0,
            "ip6-retrans-time": 0,
            "ip6-default-life": 1800,
            "ip6-hop-limit": 0,
            "autoconf": "disable",
            "unique-autoconf-addr": "disable",
            "interface-identifier": "::",
            "ip6-upstream-interface": "",
            "ip6-subnet": "::\\/0",
            "ip6-prefix-list": [],
            "ip6-delegated-prefix-list": [],
            "dhcp6-relay-service": "disable",
            "dhcp6-relay-type": "regular",
            "dhcp6-relay-ip": "",
            "dhcp6-client-options": "",
            "dhcp6-prefix-delegation": "disable",
            "dhcp6-information-request": "disable",
            "dhcp6-prefix-hint": "::\\/0",
            "dhcp6-prefix-hint-plt": 604800,
            "dhcp6-prefix-hint-vlt": 2592000,
            "vrrp-virtual-mac6": "disable",
            "vrip6_link_local": "::",
            "vrrp6": [],
        },
    },
    {
        "name": "port2",
        "q_origin_key": "port2",
        "vdom": "root",
        "vrf": 0,
        "cli-conn-status": 0,
        "fortilink": "disable",
        "switch-controller-source-ip": "outbound",
        "mode": "static",
        "client-options": [],
        "distance": 5,
        "priority": 0,
        "dhcp-relay-interface-select-method": "auto",
        "dhcp-relay-interface": "",
        "dhcp-relay-service": "disable",
        "dhcp-relay-ip": "",
        "dhcp-relay-type": "regular",
        "dhcp-relay-agent-option": "enable",
        "management-ip": "0.0.0.0 0.0.0.0",
        "ip": "172.16.4.101 255.255.255.224",
        "allowaccess": "ping probe-response",
        "gwdetect": "disable",
        "ping-serv-status": 0,
        "detectserver": "",
        "detectprotocol": "ping",
        "ha-priority": 1,
        "fail-detect": "disable",
        "fail-detect-option": "link-down",
        "fail-alert-method": "link-down",
        "fail-action-on-extender": "soft-restart",
        "fail-alert-interfaces": [],
        "dhcp-client-identifier": "",
        "dhcp-renew-time": 0,
        "ipunnumbered": "0.0.0.0",
        "username": "",
        "pppoe-unnumbered-negotiate": "enable",
        "password": "",
        "idle-timeout": 0,
        "detected-peer-mtu": 0,
        "disc-retry-timeout": 1,
        "padt-retry-timeout": 1,
        "service-name": "",
        "ac-name": "",
        "lcp-echo-interval": 5,
        "lcp-max-echo-fails": 3,
        "defaultgw": "enable",
        "dns-server-override": "enable",
        "auth-type": "auto",
        "pptp-client": "disable",
        "pptp-user": "",
        "pptp-password": "",
        "pptp-server-ip": "0.0.0.0",
        "pptp-auth-type": "auto",
        "pptp-timeout": 0,
        "arpforward": "enable",
        "ndiscforward": "enable",
        "broadcast-forward": "disable",
        "bfd": "global",
        "bfd-desired-min-tx": 250,
        "bfd-detect-mult": 3,
        "bfd-required-min-rx": 250,
        "l2forward": "disable",
        "icmp-send-redirect": "enable",
        "icmp-accept-redirect": "enable",
        "vlanforward": "disable",
        "stpforward": "disable",
        "stpforward-mode": "rpl-all-ext-id",
        "ips-sniffer-mode": "disable",
        "ident-accept": "disable",
        "ipmac": "disable",
        "subst": "disable",
        "macaddr": "",
        "substitute-dst-mac": "00:00:00:00:00:00",
        "speed": "auto",
        "status": "up",
        "netbios-forward": "disable",
        "wins-ip": "0.0.0.0",
        "type": "physical",
        "dedicated-to": "none",
        "trust-ip-1": "0.0.0.0 0.0.0.0",
        "trust-ip-2": "0.0.0.0 0.0.0.0",
        "trust-ip-3": "0.0.0.0 0.0.0.0",
        "trust-ip6-1": "::\\/0",
        "trust-ip6-2": "::\\/0",
        "trust-ip6-3": "::\\/0",
        "mtu-override": "disable",
        "mtu": 1500,
        "ring-rx": 0,
        "ring-tx": 0,
        "wccp": "disable",
        "netflow-sampler": "both",
        "sflow-sampler": "disable",
        "drop-overlapped-fragment": "disable",
        "drop-fragment": "disable",
        "src-check": "enable",
        "sample-rate": 2000,
        "polling-interval": 20,
        "sample-direction": "both",
        "explicit-web-proxy": "disable",
        "explicit-ftp-proxy": "disable",
        "proxy-captive-portal": "disable",
        "tcp-mss": 0,
        "inbandwidth": 0,
        "outbandwidth": 0,
        "egress-shaping-profile": "",
        "ingress-shaping-profile": "",
        "disconnect-threshold": 0,
        "spillover-threshold": 0,
        "ingress-spillover-threshold": 0,
        "weight": 0,
        "interface": "",
        "external": "disable",
        "vlan-protocol": "8021q",
        "vlanid": 0,
        "forward-domain": 0,
        "remote-ip": "0.0.0.0 0.0.0.0",
        "member": [],
        "lacp-mode": "active",
        "lacp-ha-slave": "enable",
        "lacp-speed": "slow",
        "min-links": 1,
        "min-links-down": "operational",
        "algorithm": "L4",
        "link-up-delay": 50,
        "priority-override": "enable",
        "devindex": 4,
        "vindex": 0,
        "description": "",
        "alias": "transit",
        "security-mode": "none",
        "captive-portal": 0,
        "security-mac-auth-bypass": "disable",
        "security-external-web": "",
        "security-external-logout": "",
        "replacemsg-override-group": "",
        "security-redirect-url": "",
        "security-exempt-list": "",
        "security-groups": [],
        "device-identification": "disable",
        "device-user-identification": "enable",
        "lldp-reception": "vdom",
        "lldp-transmission": "vdom",
        "lldp-network-policy": "",
        "estimated-upstream-bandwidth": 0,
        "estimated-downstream-bandwidth": 0,
        "measured-upstream-bandwidth": 0,
        "measured-downstream-bandwidth": 0,
        "bandwidth-measure-time": 0,
        "monitor-bandwidth": "enable",
        "vrrp-virtual-mac": "disable",
        "vrrp": [],
        "role": "undefined",
        "snmp-index": 2,
        "secondary-IP": "disable",
        "secondaryip": [],
        "preserve-session-route": "disable",
        "auto-auth-extension-device": "disable",
        "ap-discover": "enable",
        "fortilink-stacking": "enable",
        "fortilink-neighbor-detect": "fortilink",
        "ip-managed-by-fortiipam": "disable",
        "managed-subnetwork-size": "256",
        "fortilink-split-interface": "enable",
        "internal": 0,
        "fortilink-backup-link": 0,
        "switch-controller-access-vlan": "disable",
        "switch-controller-traffic-policy": "",
        "switch-controller-rspan-mode": "disable",
        "switch-controller-mgmt-vlan": 4094,
        "switch-controller-igmp-snooping": "disable",
        "switch-controller-igmp-snooping-proxy": "disable",
        "switch-controller-igmp-snooping-fast-leave": "disable",
        "switch-controller-dhcp-snooping": "disable",
        "switch-controller-dhcp-snooping-verify-mac": "disable",
        "switch-controller-dhcp-snooping-option82": "disable",
        "switch-controller-arp-inspection": "disable",
        "switch-controller-learning-limit": 0,
        "switch-controller-nac": "",
        "switch-controller-feature": "none",
        "switch-controller-iot-scanning": "disable",
        "swc-vlan": 0,
        "swc-first-create": 0,
        "color": 0,
        "tagging": [],
        "eip": "0.0.0.0",
        "ipv6": {
            "ip6-mode": "static",
            "nd-mode": "basic",
            "nd-cert": "",
            "nd-security-level": 0,
            "nd-timestamp-delta": 300,
            "nd-timestamp-fuzz": 1,
            "nd-cga-modifier": "0065636473612D776974682D73686132",
            "ip6-dns-server-override": "enable",
            "ip6-address": "::\\/0",
            "ip6-extra-addr": [],
            "ip6-allowaccess": "",
            "ip6-send-adv": "disable",
            "icmp6-send-redirect": "enable",
            "ip6-manage-flag": "disable",
            "ip6-other-flag": "disable",
            "ip6-max-interval": 600,
            "ip6-min-interval": 198,
            "ip6-link-mtu": 0,
            "ip6-reachable-time": 0,
            "ip6-retrans-time": 0,
            "ip6-default-life": 1800,
            "ip6-hop-limit": 0,
            "autoconf": "disable",
            "unique-autoconf-addr": "disable",
            "interface-identifier": "::",
            "ip6-upstream-interface": "",
            "ip6-subnet": "::\\/0",
            "ip6-prefix-list": [],
            "ip6-delegated-prefix-list": [],
            "dhcp6-relay-service": "disable",
            "dhcp6-relay-type": "regular",
            "dhcp6-relay-ip": "",
            "dhcp6-client-options": "",
            "dhcp6-prefix-delegation": "disable",
            "dhcp6-information-request": "disable",
            "dhcp6-prefix-hint": "::\\/0",
            "dhcp6-prefix-hint-plt": 604800,
            "dhcp6-prefix-hint-vlt": 2592000,
            "vrrp-virtual-mac6": "disable",
            "vrip6_link_local": "::",
            "vrrp6": [],
        },
    },
]

routes = [
    {
        "seq-num": 24,
        "q_origin_key": 24,
        "status": "enable",
        "dst": "199.40.0.0 255.254.0.0",
        "src": "0.0.0.0 0.0.0.0",
        "gateway": "10.187.88.49",
        "distance": 10,
        "weight": 0,
        "priority": 0,
        "device": "port4",
        "comment": "CN",
        "blackhole": "disable",
        "dynamic-gateway": "disable",
        "virtual-wan-link": "disable",
        "dstaddr": "",
        "internet-service": 0,
        "internet-service-custom": "",
        "link-monitor-exempt": "disable",
        "vrf": 0,
        "bfd": "disable",
    },
    {
        "seq-num": 1,
        "q_origin_key": 1,
        "status": "enable",
        "dst": "0.0.0.0 0.0.0.0",
        "src": "0.0.0.0 0.0.0.0",
        "gateway": "172.16.0.54",
        "distance": 10,
        "weight": 0,
        "priority": 0,
        "device": "port5",
        "comment": "default to inet",
        "blackhole": "disable",
        "dynamic-gateway": "disable",
        "virtual-wan-link": "disable",
        "dstaddr": "",
        "internet-service": 0,
        "internet-service-custom": "",
        "link-monitor-exempt": "disable",
        "vrf": 0,
        "bfd": "disable",
    },
]

vips = [
    {
        "name": "vip_test",
        "q_origin_key": "vip_test",
        "id": 0,
        "uuid": "6f45a080-1e22-51e8-0f61-d8bb1fd89eac",
        "comment": "",
        "type": "static-nat",
        "dns-mapping-ttl": 0,
        "ldb-method": "static",
        "src-filter": [],
        "service": [],
        "extip": "172.29.229.129-172.29.229.142",
        "extaddr": [],
        "mappedip": [
            {
                "range": "192.168.229.129-192.168.229.142",
                "q_origin_key": "192.168.229.129-192.168.229.142",
            }
        ],
        "mapped-addr": "",
        "extintf": "port4",
        "arp-reply": "enable",
        "server-type": "",
        "http-redirect": "disable",
        "persistence": "none",
        "nat-source-vip": "disable",
        "portforward": "disable",
        "protocol": "tcp",
        "extport": "0-65535",
        "mappedport": "0-65535",
        "gratuitous-arp-interval": 0,
        "srcintf-filter": [],
        "portmapping-type": "1-to-1",
        "realservers": [],
        "http-cookie-domain-from-host": "disable",
        "http-cookie-domain": "",
        "http-cookie-path": "",
        "http-cookie-generation": 0,
        "http-cookie-age": 60,
        "http-cookie-share": "same-ip",
        "https-cookie-secure": "disable",
        "http-multiplex": "disable",
        "http-ip-header": "disable",
        "http-ip-header-name": "",
        "outlook-web-access": "disable",
        "weblogic-server": "disable",
        "websphere-server": "disable",
        "ssl-mode": "half",
        "ssl-certificate": "",
        "ssl-dh-bits": "2048",
        "ssl-algorithm": "high",
        "ssl-cipher-suites": [],
        "ssl-server-algorithm": "client",
        "ssl-server-cipher-suites": [],
        "ssl-pfs": "require",
        "ssl-min-version": "tls-1.1",
        "ssl-max-version": "tls-1.3",
        "ssl-server-min-version": "client",
        "ssl-server-max-version": "client",
        "ssl-send-empty-frags": "enable",
        "ssl-client-fallback": "enable",
        "ssl-client-renegotiation": "secure",
        "ssl-client-session-state-type": "both",
        "ssl-client-session-state-timeout": 30,
        "ssl-client-session-state-max": 1000,
        "ssl-client-rekey-count": 0,
        "ssl-server-session-state-type": "both",
        "ssl-server-session-state-timeout": 60,
        "ssl-server-session-state-max": 100,
        "ssl-http-location-conversion": "disable",
        "ssl-http-match-host": "enable",
        "ssl-hpkp": "disable",
        "ssl-hpkp-primary": "",
        "ssl-hpkp-backup": "",
        "ssl-hpkp-age": 5184000,
        "ssl-hpkp-report-uri": "",
        "ssl-hpkp-include-subdomains": "disable",
        "ssl-hsts": "disable",
        "ssl-hsts-age": 5184000,
        "ssl-hsts-include-subdomains": "disable",
        "monitor": [],
        "max-embryonic-connections": 1000,
        "color": 0,
    },
    {
        "name": "vip_test_2",
        "q_origin_key": "vip_test_2",
        "id": 0,
        "uuid": "6f45a080-1e22-51e8-0f61-d8bb1fd89eac",
        "comment": "",
        "type": "static-nat",
        "dns-mapping-ttl": 0,
        "ldb-method": "static",
        "src-filter": [],
        "service": [],
        "extip": "172.29.22.129-172.29.22.142",
        "extaddr": [],
        "mappedip": [
            {
                "range": "192.168.22.129-192.168.22.142",
                "q_origin_key": "192.168.229.129-192.168.229.142",
            }
        ],
        "mapped-addr": "",
        "extintf": "port4",
        "arp-reply": "enable",
        "server-type": "",
        "http-redirect": "disable",
        "persistence": "none",
        "nat-source-vip": "disable",
        "portforward": "disable",
        "protocol": "tcp",
        "extport": "0-65535",
        "mappedport": "0-65535",
        "gratuitous-arp-interval": 0,
        "srcintf-filter": [],
        "portmapping-type": "1-to-1",
        "realservers": [],
        "http-cookie-domain-from-host": "disable",
        "http-cookie-domain": "",
        "http-cookie-path": "",
        "http-cookie-generation": 0,
        "http-cookie-age": 60,
        "http-cookie-share": "same-ip",
        "https-cookie-secure": "disable",
        "http-multiplex": "disable",
        "http-ip-header": "disable",
        "http-ip-header-name": "",
        "outlook-web-access": "disable",
        "weblogic-server": "disable",
        "websphere-server": "disable",
        "ssl-mode": "half",
        "ssl-certificate": "",
        "ssl-dh-bits": "2048",
        "ssl-algorithm": "high",
        "ssl-cipher-suites": [],
        "ssl-server-algorithm": "client",
        "ssl-server-cipher-suites": [],
        "ssl-pfs": "require",
        "ssl-min-version": "tls-1.1",
        "ssl-max-version": "tls-1.3",
        "ssl-server-min-version": "client",
        "ssl-server-max-version": "client",
        "ssl-send-empty-frags": "enable",
        "ssl-client-fallback": "enable",
        "ssl-client-renegotiation": "secure",
        "ssl-client-session-state-type": "both",
        "ssl-client-session-state-timeout": 30,
        "ssl-client-session-state-max": 1000,
        "ssl-client-rekey-count": 0,
        "ssl-server-session-state-type": "both",
        "ssl-server-session-state-timeout": 60,
        "ssl-server-session-state-max": 100,
        "ssl-http-location-conversion": "disable",
        "ssl-http-match-host": "enable",
        "ssl-hpkp": "disable",
        "ssl-hpkp-primary": "",
        "ssl-hpkp-backup": "",
        "ssl-hpkp-age": 5184000,
        "ssl-hpkp-report-uri": "",
        "ssl-hpkp-include-subdomains": "disable",
        "ssl-hsts": "disable",
        "ssl-hsts-age": 5184000,
        "ssl-hsts-include-subdomains": "disable",
        "monitor": [],
        "max-embryonic-connections": 1000,
        "color": 0,
    },
]

vip_groups = [
    {
        "name": "vip group 1",
        "q_origin_key": "vip group 1",
        "uuid": "5d4aafce-050d-51e9-0546-47cd7b384c80",
        "interface": "port4",
        "color": 0,
        "comments": "test comment",
        "member": [
            {"name": "vip_test", "q_origin_key": "vip_test"},
            {"name": "vip_test_2", "q_origin_key": "vip_test_2"},
        ],
    },
    {
        "name": "vip group 2",
        "q_origin_key": "vip group 2",
        "uuid": "5d4aafce-050d-51e9-0546-47cd7b384c80",
        "interface": "port4",
        "color": 0,
        "comments": "test comment",
        "member": [
            {"name": "vip group 1", "q_origin_key": "vip group 1"},
        ],
    },
    {
        "name": "vip group 3",
        "q_origin_key": "vip group 3",
        "uuid": "5d4aafce-050d-51e9-0546-47cd7b384c80",
        "interface": "port4",
        "color": 0,
        "comments": "test comment",
        "member": [
            {"name": "vip_test", "q_origin_key": "vip_test"},
            {"name": "vip group 1", "q_origin_key": "vip group 1"},
        ],
    },
]

services = [
    {
        "name": "DNS",
        "q_origin_key": "DNS",
        "proxy": "disable",
        "category": "Network Services",
        "protocol": "TCP/UDP/SCTP",
        "helper": "auto",
        "iprange": "0.0.0.0",
        "fqdn": "",
        "tcp-portrange": "53",
        "udp-portrange": "53",
        "sctp-portrange": "",
        "tcp-halfclose-timer": 0,
        "tcp-halfopen-timer": 0,
        "tcp-timewait-timer": 0,
        "udp-idle-timer": 0,
        "session-ttl": "0",
        "check-reset-range": "default",
        "comment": "",
        "color": 0,
        "visibility": "enable",
        "app-service-type": "disable",
        "app-category": [],
        "application": [],
    },
    {
        "name": "HTTP",
        "q_origin_key": "HTTP",
        "proxy": "disable",
        "category": "Web Access",
        "protocol": "TCP/UDP/SCTP",
        "helper": "auto",
        "iprange": "0.0.0.0",
        "fqdn": "",
        "tcp-portrange": "80",
        "udp-portrange": "",
        "sctp-portrange": "",
        "tcp-halfclose-timer": 0,
        "tcp-halfopen-timer": 0,
        "tcp-timewait-timer": 0,
        "udp-idle-timer": 0,
        "session-ttl": "0",
        "check-reset-range": "default",
        "comment": "",
        "color": 0,
        "visibility": "enable",
        "app-service-type": "disable",
        "app-category": [],
        "application": [],
    },
    {
        "name": "PING",
        "q_origin_key": "PING",
        "proxy": "disable",
        "category": "Network Services",
        "protocol": "ICMP",
        "helper": "auto",
        "iprange": "0.0.0.0",
        "fqdn": "",
        "icmptype": 8,
        "icmpcode": "",
        "tcp-halfclose-timer": 0,
        "tcp-halfopen-timer": 0,
        "tcp-timewait-timer": 0,
        "udp-idle-timer": 0,
        "session-ttl": "0",
        "check-reset-range": "default",
        "comment": "",
        "color": 0,
        "visibility": "enable",
        "app-service-type": "disable",
        "app-category": [],
        "application": [],
    },
    {
        "name": "webproxy",
        "q_origin_key": "webproxy",
        "proxy": "enable",
        "category": "Web Proxy",
        "protocol": "ALL",
        "helper": "auto",
        "iprange": "0.0.0.0",
        "fqdn": "",
        "tcp-portrange": "0-65535:0-65535",
        "tcp-halfclose-timer": 0,
        "tcp-halfopen-timer": 0,
        "tcp-timewait-timer": 0,
        "udp-idle-timer": 0,
        "session-ttl": "0",
        "check-reset-range": "default",
        "comment": "",
        "color": 0,
        "visibility": "enable",
        "app-service-type": "disable",
        "app-category": [],
        "application": [],
        "fabric-object": "disable",
    },
    {
        "name": "proxy_https",
        "q_origin_key": "proxy_https",
        "proxy": "enable",
        "category": "Web Proxy",
        "protocol": "ALL",
        "helper": "auto",
        "iprange": "0.0.0.0",
        "fqdn": "",
        "tcp-portrange": "443",
        "tcp-halfclose-timer": 0,
        "tcp-halfopen-timer": 0,
        "tcp-timewait-timer": 0,
        "udp-idle-timer": 0,
        "session-ttl": "0",
        "check-reset-range": "default",
        "comment": "",
        "color": 0,
        "visibility": "enable",
        "app-service-type": "disable",
        "app-category": [],
        "application": [],
        "fabric-object": "disable",
    },
    {
        "name": "ALL_ICMP6",
        "q_origin_key": "ALL_ICMP6",
        "proxy": "disable",
        "category": "General",
        "protocol": "ICMP6",
        "helper": "auto",
        "iprange": "0.0.0.0",
        "fqdn": "",
        "icmptype": "",
        "tcp-halfclose-timer": 0,
        "tcp-halfopen-timer": 0,
        "tcp-timewait-timer": 0,
        "udp-idle-timer": 0,
        "session-ttl": "0",
        "check-reset-range": "default",
        "comment": "",
        "color": 0,
        "visibility": "enable",
        "app-service-type": "disable",
        "app-category": [],
        "application": [],
        "fabric-object": "disable",
    },
    {
        "name": "GRE",
        "q_origin_key": "GRE",
        "proxy": "disable",
        "category": "Tunneling",
        "protocol": "IP",
        "helper": "auto",
        "iprange": "0.0.0.0",
        "fqdn": "",
        "protocol-number": 47,
        "tcp-halfclose-timer": 0,
        "tcp-halfopen-timer": 0,
        "tcp-timewait-timer": 0,
        "udp-idle-timer": 0,
        "session-ttl": "0",
        "check-reset-range": "default",
        "comment": "",
        "color": 0,
        "visibility": "enable",
        "app-service-type": "disable",
        "app-category": [],
        "application": [],
        "fabric-object": "disable",
    },
]

service_groups = [
    {
        "name": "service group 1",
        "q_origin_key": "service group 1",
        "member": [
            {"name": "HTTP", "q_origin_key": "HTTP"},
            {"name": "DNS", "q_origin_key": "DNS"},
        ],
        "proxy": "disable",
        "comment": "",
        "color": 0,
    },
    {
        "name": "service group 2",
        "q_origin_key": "service group 2",
        "member": [
            {"name": "service group 1", "q_origin_key": "service group 1"},
        ],
        "proxy": "disable",
        "comment": "",
        "color": 0,
    },
    {
        "name": "service group 3",
        "q_origin_key": "service group 3",
        "member": [
            {"name": "HTTP", "q_origin_key": "HTTP"},
            {"name": "service group 1", "q_origin_key": "service group 1"},
        ],
        "proxy": "disable",
        "comment": "",
        "color": 0,
    },
]

ippools = [
    {
        "name": "Post_DynCom-SNAT",
        "q_origin_key": "Post_DynCom-SNAT",
        "type": "overload",
        "startip": "10.197.113.240",
        "endip": "10.197.113.240",
        "source-startip": "0.0.0.0",
        "source-endip": "0.0.0.0",
        "block-size": 128,
        "num-blocks-per-user": 8,
        "pba-timeout": 30,
        "permit-any-host": "disable",
        "arp-reply": "enable",
        "arp-intf": "",
        "associated-interface": "",
        "comments": "",
    },
    {
        "name": "Post_DynCom-SNAT_reverse",
        "q_origin_key": "Post_DynCom-SNAT_reverse",
        "type": "overload",
        "startip": "172.29.222.42",
        "endip": "172.29.222.42",
        "source-startip": "0.0.0.0",
        "source-endip": "0.0.0.0",
        "block-size": 128,
        "num-blocks-per-user": 8,
        "pba-timeout": 30,
        "permit-any-host": "disable",
        "arp-reply": "enable",
        "arp-intf": "",
        "associated-interface": "",
        "comments": "mtnu 20190227 2019022670002913",
    },
]

policies = [
    {
        "policyid": 35,
        "q_origin_key": 35,
        "name": "policy 1",
        "uuid": "6f598f5a-1e22-51e8-0121-de7f9edc81cd",
        "srcintf": [{"name": "port4", "q_origin_key": "port4"}],
        "dstintf": [{"name": "port5", "q_origin_key": "port5"}],
        "srcaddr": [
            {"name": "NET_199.40.1.0_24", "q_origin_key": "NET_199.40.1.0_24"}
        ],
        "dstaddr": [
            {
                "name": "NET_198.141.216.0_22",
                "q_origin_key": "NET_198.141.216.0_22",
            },
            {
                "name": "RANGE_10.188.128.106-108",
                "q_origin_key": "RANGE_10.188.128.106-108",
            },
        ],
        "internet-service": "disable",
        "internet-service-id": [],
        "internet-service-group": [],
        "internet-service-custom": [],
        "internet-service-custom-group": [],
        "internet-service-src": "disable",
        "internet-service-src-id": [],
        "internet-service-src-group": [],
        "internet-service-src-custom": [],
        "internet-service-src-custom-group": [],
        "reputation-minimum": 0,
        "reputation-direction": "destination",
        "rtp-nat": "disable",
        "rtp-addr": [],
        "action": "accept",
        "send-deny-packet": "disable",
        "firewall-session-dirty": "check-all",
        "status": "enable",
        "schedule": "always",
        "schedule-timeout": "disable",
        "service": [{"name": "HTTP", "q_origin_key": "HTTP"}],
        "tos": "0x00",
        "tos-mask": "0x00",
        "tos-negate": "disable",
        "anti-replay": "enable",
        "tcp-session-without-syn": "disable",
        "geoip-anycast": "disable",
        "utm-status": "disable",
        "inspection-mode": "flow",
        "http-policy-redirect": "disable",
        "ssh-policy-redirect": "disable",
        "webproxy-profile": "",
        "profile-type": "single",
        "profile-group": "",
        "profile-protocol-options": "default",
        "ssl-ssh-profile": "no-inspection",
        "av-profile": "",
        "webfilter-profile": "",
        "dnsfilter-profile": "",
        "emailfilter-profile": "",
        "dlp-sensor": "",
        "ips-sensor": "",
        "application-list": "",
        "voip-profile": "",
        "icap-profile": "",
        "cifs-profile": "",
        "waf-profile": "",
        "ssh-filter-profile": "",
        "logtraffic": "all",
        "logtraffic-start": "disable",
        "auto-asic-offload": "enable",
        "np-acceleration": "enable",
        "webproxy-forward-server": "",
        "traffic-shaper": "",
        "traffic-shaper-reverse": "",
        "per-ip-shaper": "",
        "application": [],
        "app-category": [],
        "url-category": [],
        "app-group": [],
        "nat": "enable",
        "permit-any-host": "disable",
        "permit-stun-host": "disable",
        "fixedport": "disable",
        "ippool": "enable",
        "poolname": [
            {"name": "Post_DynCom-SNAT", "q_origin_key": "Post_DynCom-SNAT"}
        ],
        "session-ttl": "0",
        "vlan-cos-fwd": 255,
        "vlan-cos-rev": 255,
        "inbound": "disable",
        "outbound": "enable",
        "natinbound": "disable",
        "natoutbound": "disable",
        "wccp": "disable",
        "ntlm": "disable",
        "ntlm-guest": "disable",
        "ntlm-enabled-browsers": [],
        "fsso": "enable",
        "wsso": "enable",
        "rsso": "disable",
        "fsso-agent-for-ntlm": "",
        "groups": [],
        "users": [],
        "fsso-groups": [],
        "auth-path": "disable",
        "disclaimer": "disable",
        "email-collect": "disable",
        "vpntunnel": "",
        "natip": "0.0.0.0 0.0.0.0",
        "match-vip": "disable",
        "match-vip-only": "disable",
        "diffserv-forward": "disable",
        "diffserv-reverse": "disable",
        "diffservcode-forward": "000000",
        "diffservcode-rev": "000000",
        "tcp-mss-sender": 0,
        "tcp-mss-receiver": 0,
        "comments": "rgi 20141120 2014102270001675",
        "label": "",
        "global-label": "",
        "auth-cert": "",
        "auth-redirect-addr": "",
        "redirect-url": "",
        "identity-based-route": "",
        "block-notification": "disable",
        "custom-log-fields": [],
        "replacemsg-override-group": "",
        "srcaddr-negate": "disable",
        "dstaddr-negate": "disable",
        "service-negate": "disable",
        "internet-service-negate": "disable",
        "internet-service-src-negate": "disable",
        "timeout-send-rst": "disable",
        "captive-portal-exempt": "disable",
        "ssl-mirror": "disable",
        "ssl-mirror-intf": [],
        "dsri": "disable",
        "radius-mac-auth-bypass": "disable",
        "delay-tcp-npu-session": "disable",
        "vlan-filter": "",
    },
    {
        "policyid": 107,
        "q_origin_key": 107,
        "name": "policy 1",
        "uuid": "6f598f5a-1e22-51e8-0121-de7f9edc81cd",
        "srcintf": [{"name": "port4", "q_origin_key": "port4"}],
        "dstintf": [{"name": "port5", "q_origin_key": "port5"}],
        "srcaddr": [
            {"name": "NET_199.40.1.0_24", "q_origin_key": "NET_199.40.1.0_24"}
        ],
        "dstaddr": [
            {
                "name": "NET_198.141.216.0_22",
                "q_origin_key": "NET_198.141.216.0_22",
            },
        ],
        "internet-service": "disable",
        "internet-service-id": [],
        "internet-service-group": [],
        "internet-service-custom": [],
        "internet-service-custom-group": [],
        "internet-service-src": "disable",
        "internet-service-src-id": [],
        "internet-service-src-group": [],
        "internet-service-src-custom": [],
        "internet-service-src-custom-group": [],
        "reputation-minimum": 0,
        "reputation-direction": "destination",
        "rtp-nat": "disable",
        "rtp-addr": [],
        "action": "accept",
        "send-deny-packet": "disable",
        "firewall-session-dirty": "check-all",
        "status": "enable",
        "schedule": "always",
        "schedule-timeout": "disable",
        "service": [{"name": "HTTP", "q_origin_key": "HTTP"}],
        "tos": "0x00",
        "tos-mask": "0x00",
        "tos-negate": "disable",
        "anti-replay": "enable",
        "tcp-session-without-syn": "disable",
        "geoip-anycast": "disable",
        "utm-status": "disable",
        "inspection-mode": "flow",
        "http-policy-redirect": "disable",
        "ssh-policy-redirect": "disable",
        "webproxy-profile": "",
        "profile-type": "single",
        "profile-group": "",
        "profile-protocol-options": "default",
        "ssl-ssh-profile": "no-inspection",
        "av-profile": "",
        "webfilter-profile": "",
        "dnsfilter-profile": "",
        "emailfilter-profile": "",
        "dlp-sensor": "",
        "ips-sensor": "",
        "application-list": "",
        "voip-profile": "",
        "icap-profile": "",
        "cifs-profile": "",
        "waf-profile": "",
        "ssh-filter-profile": "",
        "logtraffic": "all",
        "logtraffic-start": "disable",
        "auto-asic-offload": "enable",
        "np-acceleration": "enable",
        "webproxy-forward-server": "",
        "traffic-shaper": "",
        "traffic-shaper-reverse": "",
        "per-ip-shaper": "",
        "application": [],
        "app-category": [],
        "url-category": [],
        "app-group": [],
        "nat": "enable",
        "permit-any-host": "disable",
        "permit-stun-host": "disable",
        "fixedport": "disable",
        "ippool": "enable",
        "poolname": [
            {"name": "Post_DynCom-SNAT", "q_origin_key": "Post_DynCom-SNAT"}
        ],
        "session-ttl": "0",
        "vlan-cos-fwd": 255,
        "vlan-cos-rev": 255,
        "inbound": "disable",
        "outbound": "enable",
        "natinbound": "disable",
        "natoutbound": "disable",
        "wccp": "disable",
        "ntlm": "disable",
        "ntlm-guest": "disable",
        "ntlm-enabled-browsers": [],
        "fsso": "enable",
        "wsso": "enable",
        "rsso": "disable",
        "fsso-agent-for-ntlm": "",
        "groups": [],
        "users": [],
        "fsso-groups": [],
        "auth-path": "disable",
        "disclaimer": "disable",
        "email-collect": "disable",
        "vpntunnel": "",
        "natip": "0.0.0.0 0.0.0.0",
        "match-vip": "disable",
        "match-vip-only": "disable",
        "diffserv-forward": "disable",
        "diffserv-reverse": "disable",
        "diffservcode-forward": "000000",
        "diffservcode-rev": "000000",
        "tcp-mss-sender": 0,
        "tcp-mss-receiver": 0,
        "comments": "rgi 20141120 2014102270001675",
        "label": "",
        "global-label": "",
        "auth-cert": "",
        "auth-redirect-addr": "",
        "redirect-url": "",
        "identity-based-route": "",
        "block-notification": "disable",
        "custom-log-fields": [],
        "replacemsg-override-group": "",
        "srcaddr-negate": "disable",
        "dstaddr-negate": "disable",
        "service-negate": "disable",
        "internet-service-negate": "disable",
        "internet-service-src-negate": "disable",
        "timeout-send-rst": "disable",
        "captive-portal-exempt": "disable",
        "ssl-mirror": "disable",
        "ssl-mirror-intf": [],
        "dsri": "disable",
        "radius-mac-auth-bypass": "disable",
        "delay-tcp-npu-session": "disable",
        "vlan-filter": "",
    },
]

proxy_addresses = [
    {
        "name": "http.kali.org",
        "q_origin_key": "http.kali.org",
        "uuid": "809ccd5a-05a9-51ec-9fd9-cc35c477caa7",
        "type": "host-regex",
        "host": "",
        "host-regex": "^http\\.kali\\.org$",
        "path": "",
        "query": "",
        "referrer": "disable",
        "category": [],
        "method": "",
        "ua": "",
        "header-name": "",
        "header": "",
        "case-sensitivity": "disable",
        "header-group": [],
        "color": 0,
        "tagging": [],
        "comment": "http.kali.org",
    },
    {
        "name": "http.kali.org\\/kali",
        "q_origin_key": "http.kali.org\\/kali",
        "uuid": "809d384e-05a9-51ec-b7b9-01e501e1c19a",
        "type": "url",
        "host": "http.kali.org",
        "host-regex": "",
        "path": "\\/kali",
        "query": "",
        "referrer": "disable",
        "category": [],
        "method": "",
        "ua": "",
        "header-name": "",
        "header": "",
        "case-sensitivity": "disable",
        "header-group": [],
        "color": 0,
        "tagging": [],
        "comment": "http.kali.org\\/kali",
    },
    {
        "name": "*.azure.net",
        "q_origin_key": "*.azure.net",
        "css-class": "ftnt-address-explicit-proxy ftnt-color-0",
        "uuid": "abcef75c-5ce6-51ec-99ea-2fa6146a1046",
        "type": "host-regex",
        "host": "",
        "host-regex": "\\.azure\\.net$",
        "path": "",
        "query": "",
        "referrer": "disable",
        "category": [],
        "header-name": "",
        "header": "",
        "case-sensitivity": "disable",
        "header-group": [{"header-name": "", "header": ""}],
        "color": "0",
        "tagging": [],
        "comment": "*.azure.net",
    },
]

proxy_address_groups = [
    {
        "name": "test proxy group 1",
        "q_origin_key": "test_proxy_group_1",
        "css-class": "ftnt-address-explicit-proxy-group ftnt-color-0",
        "type": "dst",
        "uuid": "9b675b48-b196-51ec-534e-9dcda9bd3ed8",
        "member": [
            {"name": "http.kali.org"},
            {"name": "http.kali.org\\/kali"},
        ],
        "color": "0",
        "tagging": [],
        "comment": "test",
    },
    {
        "name": "test proxy group 2",
        "q_origin_key": "test_proxy_group_2",
        "css-class": "ftnt-address-explicit-proxy-group ftnt-color-0",
        "type": "dst",
        "uuid": "d0f64a70-b197-51ec-c1ed-1461ab25eede",
        "member": [{"name": "test proxy group 1"}],
        "color": "0",
        "tagging": [],
        "comment": "",
    },
    {
        "name": "test proxy group 3",
        "q_origin_key": "test_proxy_group_3",
        "css-class": "ftnt-address-explicit-proxy-group ftnt-color-0",
        "type": "dst",
        "uuid": "d0f64a70-b197-51ec-c1ed-1461ab25eede",
        "member": [
            {"name": "*.azure.net"},
            {"name": "test proxy group 1"},
        ],
        "color": "0",
        "tagging": [],
        "comment": "",
    },
]

proxy_address_groups_member_missing = [
    {
        "name": "test proxy group 1",
        "q_origin_key": "test_proxy_group_1",
        "css-class": "ftnt-address-explicit-proxy-group ftnt-color-0",
        "type": "dst",
        "uuid": "9b675b48-b196-51ec-534e-9dcda9bd3ed8",
        "member": [
            {"name": "http.kali.org"},
            {"name": "http.kali.org\\/kali"},
        ],
        "color": "0",
        "tagging": [],
        "comment": "test",
    },
    {
        "name": "test proxy group 4",
        "q_origin_key": "test_proxy_group_4",
        "css-class": "ftnt-address-explicit-proxy-group ftnt-color-0",
        "type": "dst",
        "uuid": "d0f64a70-b197-51ec-c1ed-1461ab25eede",
        "member": [
            {
                "name": "test proxy group 1",
                "q_origin_key": "test proxy group 1",
            },
            {"name": "missing member", "q_origin_key": "missing member"},
        ],
        "color": "0",
        "tagging": [],
        "comment": "",
    },
]

proxy_policies = [
    {
        "uuid": "ec2355ce-05ab-51ec-4c44-be03401e7e13",
        "policyid": 129,
        "q_origin_key": 129,
        "name": "policy 129",
        "proxy": "transparent-web",
        "srcintf": [{"name": "port2", "q_origin_key": "port2"}],
        "dstintf": [{"name": "port1", "q_origin_key": "port1"}],
        "srcaddr": [
            {
                "name": "NET_172.16.240.120_29",
                "q_origin_key": "NET_172.16.240.120_29",
            }
        ],
        "poolname": [],
        "dstaddr": [
            {"name": "http.kali.org", "q_origin_key": "http.kali.org"}
        ],
        "internet-service": "disable",
        "internet-service-negate": "disable",
        "internet-service-name": [],
        "internet-service-group": [],
        "internet-service-custom": [],
        "internet-service-custom-group": [],
        "service": [{"name": "proxy_https", "q_origin_key": "proxy_https"}],
        "srcaddr-negate": "disable",
        "dstaddr-negate": "disable",
        "service-negate": "disable",
        "action": "accept",
        "status": "enable",
        "schedule": "always",
        "logtraffic": "all",
        "session-ttl": 0,
        "srcaddr6": [],
        "dstaddr6": [],
        "groups": [],
        "users": [],
        "http-tunnel-auth": "disable",
        "ssh-policy-redirect": "disable",
        "webproxy-forward-server": "",
        "webproxy-profile": "",
        "transparent": "disable",
        "webcache": "disable",
        "webcache-https": "disable",
        "disclaimer": "disable",
        "utm-status": "enable",
        "profile-type": "group",
        "profile-group": "proxy_log",
        "profile-protocol-options": "",
        "ssl-ssh-profile": "",
        "av-profile": "",
        "webfilter-profile": "",
        "emailfilter-profile": "",
        "dlp-sensor": "",
        "file-filter-profile": "",
        "ips-sensor": "",
        "application-list": "",
        "icap-profile": "",
        "cifs-profile": "",
        "waf-profile": "",
        "ssh-filter-profile": "",
        "replacemsg-override-group": "",
        "logtraffic-start": "disable",
        "label": "",
        "global-label": "",
        "comments": "[Pentest] [unknown] [#2]",
        "redirect-url": "",
        "decrypted-traffic-mirror": "",
    },
]

phase1_interfaces = [
    {
        "name": "vpn_phase1",
        "q_origin_key": "vpn_phase1",
        "type": "static",
        "interface": "port1",
        "ip-version": "4",
        "ike-version": "2",
        "local-gw": "0.0.0.0",
        "local-gw6": "::",
        "remote-gw": "1.1.1.1",
        "remote-gw6": "::",
        "remotegw-ddns": "",
        "keylife": 86400,
        "certificate": [],
        "authmethod": "psk",
        "authmethod-remote": "",
        "mode": "main",
        "peertype": "any",
        "peerid": "",
        "default-gw": "0.0.0.0",
        "default-gw-priority": 0,
        "usrgrp": "",
        "peer": "",
        "peergrp": "",
        "monitor": [],
        "monitor-min": 0,
        "monitor-hold-down-type": "immediate",
        "monitor-hold-down-delay": 0,
        "monitor-hold-down-weekday": "sunday",
        "monitor-hold-down-time": "00:00",
        "net-device": "disable",
        "passive-mode": "disable",
        "exchange-interface-ip": "disable",
        "exchange-ip-addr4": "0.0.0.0",
        "exchange-ip-addr6": "::",
        "aggregate-member": "disable",
        "aggregate-weight": 1,
        "packet-redistribution": "disable",
        "mode-cfg": "disable",
        "mode-cfg-allow-client-selector": "disable",
        "assign-ip": "enable",
        "assign-ip-from": "range",
        "ipv4-start-ip": "0.0.0.0",
        "ipv4-end-ip": "0.0.0.0",
        "ipv4-netmask": "255.255.255.255",
        "dhcp-ra-giaddr": "0.0.0.0",
        "dhcp6-ra-linkaddr": "::",
        "dns-mode": "manual",
        "ipv4-dns-server1": "0.0.0.0",
        "ipv4-dns-server2": "0.0.0.0",
        "ipv4-dns-server3": "0.0.0.0",
        "internal-domain-list": [],
        "ipv4-wins-server1": "0.0.0.0",
        "ipv4-wins-server2": "0.0.0.0",
        "ipv4-exclude-range": [],
        "ipv4-split-include": "",
        "split-include-service": "",
        "ipv4-name": "",
        "ipv6-start-ip": "::",
        "ipv6-end-ip": "::",
        "ipv6-prefix": 128,
        "ipv6-dns-server1": "::",
        "ipv6-dns-server2": "::",
        "ipv6-dns-server3": "::",
        "ipv6-exclude-range": [],
        "ipv6-split-include": "",
        "ipv6-name": "",
        "ip-delay-interval": 0,
        "unity-support": "enable",
        "domain": "",
        "banner": "",
        "include-local-lan": "disable",
        "ipv4-split-exclude": "",
        "ipv6-split-exclude": "",
        "save-password": "disable",
        "client-auto-negotiate": "disable",
        "client-keep-alive": "disable",
        "backup-gateway": [],
        "proposal": "chacha20poly1305-prfsha256 aes256gcm-prfsha384",
        "add-route": "enable",
        "add-gw-route": "disable",
        "psksecret": "123456",
        "psksecret-remote": "",
        "keepalive": 10,
        "distance": 15,
        "priority": 1,
        "localid": "",
        "localid-type": "auto",
        "auto-negotiate": "enable",
        "negotiate-timeout": 30,
        "fragmentation": "enable",
        "ip-fragmentation": "post-encapsulation",
        "dpd": "on-demand",
        "dpd-retrycount": 3,
        "dpd-retryinterval": "20",
        "comments": "test phase1",
        "npu-offload": "enable",
        "send-cert-chain": "enable",
        "dhgrp": "20",
        "suite-b": "disable",
        "eap": "disable",
        "eap-identity": "use-id-payload",
        "eap-exclude-peergrp": "",
        "eap-cert-auth": "disable",
        "acct-verify": "disable",
        "ppk": "disable",
        "ppk-secret": "",
        "ppk-identity": "",
        "wizard-type": "custom",
        "xauthtype": "disable",
        "reauth": "disable",
        "authusr": "",
        "authpasswd": "",
        "group-authentication": "disable",
        "group-authentication-secret": "",
        "authusrgrp": "",
        "mesh-selector-type": "disable",
        "idle-timeout": "disable",
        "idle-timeoutinterval": 15,
        "ha-sync-esp-seqno": "enable",
        "fgsp-sync": "disable",
        "inbound-dscp-copy": "disable",
        "auto-discovery-sender": "disable",
        "auto-discovery-receiver": "disable",
        "auto-discovery-forwarder": "disable",
        "auto-discovery-psk": "disable",
        "auto-discovery-shortcuts": "independent",
        "auto-discovery-crossover": "allow",
        "auto-discovery-offer-interval": 5,
        "encapsulation": "none",
        "encapsulation-address": "ike",
        "encap-local-gw4": "0.0.0.0",
        "encap-local-gw6": "::",
        "encap-remote-gw4": "0.0.0.0",
        "encap-remote-gw6": "::",
        "vni": 0,
        "nattraversal": "disable",
        "esn": "disable",
        "fragmentation-mtu": 1200,
        "childless-ike": "disable",
        "azure-ad-autoconnect": "disable",
        "client-resume": "disable",
        "client-resume-interval": 1800,
        "rekey": "enable",
        "digital-signature-auth": "disable",
        "signature-hash-alg": "sha2-512 sha2-384 sha2-256 sha1",
        "rsa-signature-format": "pkcs1",
        "rsa-signature-hash-override": "disable",
        "enforce-unique-id": "disable",
        "cert-id-validation": "enable",
        "fec-egress": "disable",
        "fec-send-timeout": 5,
        "fec-base": 10,
        "fec-codec": "rs",
        "fec-redundant": 1,
        "fec-ingress": "disable",
        "fec-receive-timeout": 50,
        "fec-health-check": "",
        "fec-mapping-profile": "",
        "network-overlay": "disable",
        "network-id": 0,
        "dev-id-notification": "disable",
        "dev-id": "",
        "loopback-asymroute": "enable",
        "link-cost": 0,
        "kms": "",
        "exchange-fgt-device-id": "disable",
        "ems-sn-check": "disable",
        "cert-trust-store": "local",
        "qkd": "disable",
        "qkd-profile": "",
        "transport": "udp",
        "fortinet-esp": "disable",
        "fallback-tcp-threshold": 15,
        "remote-gw-match": "any",
        "remote-gw-country": "",
        "remote-gw6-match": "any",
        "remote-gw6-end-ip": "::",
        "remote-gw6-country": "",
        "cert-peer-username-validation": "none",
        "cert-peer-username-strip": "disable",
    },
    {
        "name": "vpn_phase1_2",
        "q_origin_key": "vpn_phase1_2",
        "type": "static",
        "interface": "port1",
        "ip-version": "4",
        "ike-version": "2",
        "local-gw": "0.0.0.0",
        "local-gw6": "::",
        "remote-gw": "2.2.2.2",
        "remote-gw6": "::",
        "remotegw-ddns": "",
        "keylife": 86400,
        "certificate": [],
        "authmethod": "psk",
        "authmethod-remote": "",
        "mode": "main",
        "peertype": "any",
        "peerid": "",
        "default-gw": "0.0.0.0",
        "default-gw-priority": 0,
        "usrgrp": "",
        "peer": "",
        "peergrp": "",
        "monitor": [],
        "monitor-min": 0,
        "monitor-hold-down-type": "immediate",
        "monitor-hold-down-delay": 0,
        "monitor-hold-down-weekday": "sunday",
        "monitor-hold-down-time": "00:00",
        "net-device": "disable",
        "passive-mode": "disable",
        "exchange-interface-ip": "disable",
        "exchange-ip-addr4": "0.0.0.0",
        "exchange-ip-addr6": "::",
        "aggregate-member": "disable",
        "aggregate-weight": 1,
        "packet-redistribution": "disable",
        "mode-cfg": "disable",
        "mode-cfg-allow-client-selector": "disable",
        "assign-ip": "enable",
        "assign-ip-from": "range",
        "ipv4-start-ip": "0.0.0.0",
        "ipv4-end-ip": "0.0.0.0",
        "ipv4-netmask": "255.255.255.255",
        "dhcp-ra-giaddr": "0.0.0.0",
        "dhcp6-ra-linkaddr": "::",
        "dns-mode": "manual",
        "ipv4-dns-server1": "0.0.0.0",
        "ipv4-dns-server2": "0.0.0.0",
        "ipv4-dns-server3": "0.0.0.0",
        "internal-domain-list": [],
        "ipv4-wins-server1": "0.0.0.0",
        "ipv4-wins-server2": "0.0.0.0",
        "ipv4-exclude-range": [],
        "ipv4-split-include": "",
        "split-include-service": "",
        "ipv4-name": "",
        "ipv6-start-ip": "::",
        "ipv6-end-ip": "::",
        "ipv6-prefix": 128,
        "ipv6-dns-server1": "::",
        "ipv6-dns-server2": "::",
        "ipv6-dns-server3": "::",
        "ipv6-exclude-range": [],
        "ipv6-split-include": "",
        "ipv6-name": "",
        "ip-delay-interval": 0,
        "unity-support": "enable",
        "domain": "",
        "banner": "",
        "include-local-lan": "disable",
        "ipv4-split-exclude": "",
        "ipv6-split-exclude": "",
        "save-password": "disable",
        "client-auto-negotiate": "disable",
        "client-keep-alive": "disable",
        "backup-gateway": [],
        "proposal": "chacha20poly1305-prfsha256 aes256gcm-prfsha384",
        "add-route": "enable",
        "add-gw-route": "disable",
        "psksecret": "123456",
        "psksecret-remote": "",
        "keepalive": 10,
        "distance": 15,
        "priority": 1,
        "localid": "",
        "localid-type": "auto",
        "auto-negotiate": "enable",
        "negotiate-timeout": 30,
        "fragmentation": "enable",
        "ip-fragmentation": "post-encapsulation",
        "dpd": "on-demand",
        "dpd-retrycount": 3,
        "dpd-retryinterval": "20",
        "comments": "",
        "npu-offload": "enable",
        "send-cert-chain": "enable",
        "dhgrp": "20",
        "suite-b": "disable",
        "eap": "disable",
        "eap-identity": "use-id-payload",
        "eap-exclude-peergrp": "",
        "eap-cert-auth": "disable",
        "acct-verify": "disable",
        "ppk": "disable",
        "ppk-secret": "",
        "ppk-identity": "",
        "wizard-type": "custom",
        "xauthtype": "disable",
        "reauth": "disable",
        "authusr": "",
        "authpasswd": "",
        "group-authentication": "disable",
        "group-authentication-secret": "",
        "authusrgrp": "",
        "mesh-selector-type": "disable",
        "idle-timeout": "disable",
        "idle-timeoutinterval": 15,
        "ha-sync-esp-seqno": "enable",
        "fgsp-sync": "disable",
        "inbound-dscp-copy": "disable",
        "auto-discovery-sender": "disable",
        "auto-discovery-receiver": "disable",
        "auto-discovery-forwarder": "disable",
        "auto-discovery-psk": "disable",
        "auto-discovery-shortcuts": "independent",
        "auto-discovery-crossover": "allow",
        "auto-discovery-offer-interval": 5,
        "encapsulation": "none",
        "encapsulation-address": "ike",
        "encap-local-gw4": "0.0.0.0",
        "encap-local-gw6": "::",
        "encap-remote-gw4": "0.0.0.0",
        "encap-remote-gw6": "::",
        "vni": 0,
        "nattraversal": "disable",
        "esn": "disable",
        "fragmentation-mtu": 1200,
        "childless-ike": "disable",
        "azure-ad-autoconnect": "disable",
        "client-resume": "disable",
        "client-resume-interval": 1800,
        "rekey": "enable",
        "digital-signature-auth": "disable",
        "signature-hash-alg": "sha2-512 sha2-384 sha2-256 sha1",
        "rsa-signature-format": "pkcs1",
        "rsa-signature-hash-override": "disable",
        "enforce-unique-id": "disable",
        "cert-id-validation": "enable",
        "fec-egress": "disable",
        "fec-send-timeout": 5,
        "fec-base": 10,
        "fec-codec": "rs",
        "fec-redundant": 1,
        "fec-ingress": "disable",
        "fec-receive-timeout": 50,
        "fec-health-check": "",
        "fec-mapping-profile": "",
        "network-overlay": "disable",
        "network-id": 0,
        "dev-id-notification": "disable",
        "dev-id": "",
        "loopback-asymroute": "enable",
        "link-cost": 0,
        "kms": "",
        "exchange-fgt-device-id": "disable",
        "ems-sn-check": "disable",
        "cert-trust-store": "local",
        "qkd": "disable",
        "qkd-profile": "",
        "transport": "udp",
        "fortinet-esp": "disable",
        "fallback-tcp-threshold": 15,
        "remote-gw-match": "any",
        "remote-gw-country": "",
        "remote-gw6-match": "any",
        "remote-gw6-end-ip": "::",
        "remote-gw6-country": "",
        "cert-peer-username-validation": "none",
        "cert-peer-username-strip": "disable",
    },
]

phase2_interfaces = [
    {
        "name": "vpn_phase2",
        "q_origin_key": "vpn_phase2",
        "phase1name": "vpn_phase1",
        "dhcp-ipsec": "disable",
        "proposal": "chacha20poly1305 aes256gcm",
        "pfs": "enable",
        "ipv4-df": "disable",
        "dhgrp": "20",
        "replay": "enable",
        "keepalive": "disable",
        "auto-negotiate": "enable",
        "add-route": "phase1",
        "inbound-dscp-copy": "phase1",
        "auto-discovery-sender": "phase1",
        "auto-discovery-forwarder": "phase1",
        "keylifeseconds": 43200,
        "keylifekbs": 5120,
        "keylife-type": "seconds",
        "single-source": "disable",
        "route-overlap": "use-new",
        "encapsulation": "tunnel-mode",
        "l2tp": "disable",
        "comments": "test phase2",
        "initiator-ts-narrow": "disable",
        "diffserv": "disable",
        "diffservcode": "000000",
        "protocol": 0,
        "src-name": "",
        "src-name6": "",
        "src-addr-type": "subnet",
        "src-end-ip6": "::",
        "src-subnet": "10.0.0.0 255.0.0.0",
        "src-port": 0,
        "dst-name": "",
        "dst-name6": "",
        "dst-addr-type": "subnet",
        "dst-end-ip6": "::",
        "dst-subnet": "192.168.100.0 255.255.255.0",
        "dst-port": 0,
    }
]
